### ISSUE TITLE
cunet brightness bug in R4

### ISSUE THREAD

**Issue by dnjulek** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#10]
The current cunet-model makes the output darker than it should be, this did not happen in version R3.2
sample: https://i.slow.pics/20wfvWlW.png

```py
src = core.imwri.Read("sample.png")
rgbs = src.resize.Point(format=vs.RGBS)
spline = rgbs.resize.Spline36(1920, 1080)
w2x = rgbs.w2xnvk.Waifu2x(noise=-1, scale=2, model=2, tile_size=180, precision=32)

src_y = rgbs.resize.Point(format=vs.YUV444PS, matrix=1).std.ShufflePlanes([0], vs.GRAY)
spline_y = spline.resize.Point(format=vs.YUV444PS, matrix=1).std.ShufflePlanes([0], vs.GRAY)
w2x_y = w2x.resize.Point(format=vs.YUV444PS, matrix=1).std.ShufflePlanes([0], vs.GRAY)

w2x_y.set_output()
```
comp: https://slow.pics/c/UEcNJto8

The opposite happened with model=0/1, they were too bright in R3.2 and are right in R4: 
model 0: https://slow.pics/c/NhIQi6jX
model 1: https://slow.pics/c/TSqSva5h

More infos: https://github.com/AmusementClub/vs-mlrt/issues/2

**Comment by nlzy** [comment]
The result of R4 is correct one.

In versions prior to R4, all pixel value added about 0.00196 incorrectly. This bug fixed in https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/commit/2bec04908a1e6f12ef0f44a9a2e71ae2990ac2fc

**Comment by nlzy** [comment]
In all the pictures you provided, the difference of R3.2 and R4 is 0.00196 exactly in `PlaneStatsAverage` and `PlaneStatsMax` both.
