### ISSUE TITLE
Import newest NCNN for performance improvements

### ISSUE THREAD

**Issue by Tsubajashi** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#11]
nihui and others worked on new NCNN Updates to improve performance a good bit.
Would be cool if you implement this change in your vapoursynth Plugin.

Thanks in advance,
Tsuba

**Comment by nlzy** [comment]
Done in https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/commit/310238bff6ce7419d80fcdf837449a6da04c1151

A new release is published.
