### ISSUE TITLE
scale pow2

### ISSUE THREAD

**Issue by Selur** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#2]
would be nice if scale would not just support 1 and 2, but also 4, 8, 16,... by applying the filtering multiple times.
(Yes, this could be done by applying the Filter itself, but it should be faster when done directly in the code without the need to copy the image out of the gpu memory,..)

**Comment by nlzy** [comment]
No plans for this.
Such features mainly depends on the [upstream project](https://github.com/nihui/waifu2x-ncnn-vulkan).
