### ISSUE TITLE
No longer builds against upstream Tencent/ncnn master

### ISSUE THREAD

**Issue by gloriousbreak** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#3]
The ncnn::Pipeline::create() signature changed in Tencent/ncnn@1ea9de3, resulting in waifu2x-ncnn-vulkan failing to build. An easy solution to this is modifying the build instructions to specify a known working commit or tag.

**Comment by nlzy** [comment]
Fixed in https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/commit/3b36a08f77a70d4d6243d86c1e29d5ab6fe68025
Thanks
