### ISSUE TITLE
Request 4x or more multiples scale and TTA Mode. / Noise option question.

### ISSUE THREAD

**Issue by ghost** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#7]
The latest waifu2x-ncnn-vulkan (20210521) supports 4x or more multiples scale, can I add it when the next release of waifu2x-ncnn-vulkan appears?
And the TTA mode is not visible. can you add it?

The denoise options notation is `-1 = none` `0 = low` `1 = medium` `2 = high` `3 = highest` , but I know that -1 is an automatic option and 0 is an option to disable denoise.
So I think the notation `-1 = auto` `0 = none` `1 = low` `2 = medium` `3 = high` is correct.
It's trivial, but can you fix it?

**Comment by nlzy** [comment]
The only way to get more than 2x scale is to apply waifu2x multiple times. It is very easy to apply filters multiple times in vpy script. There is no difference through vapoursynth or plugin built-in options.

The denoise options is consistent with upstream (waifu2x-ncnn-vulkan) and the other two vapoursynth waifu2x plugins (VapourSynth-Waifu2x-caffe / VapourSynth-Waifu2x-w2xc), I think there is no reason to change this.

I will add TAA mode when I have time, I am too busy (in real life)...

**Comment by nlzy** [comment]
TTA mode added.
