### ISSUE TITLE
Pixel values should be clamped prior to processing

### ISSUE THREAD

**Issue by ghost** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#8]
Clips with out of range pixels are very common, and will cause artifacts when processed by waifu2x.

**Comment by nlzy** [comment]
Fixed in https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/commit/47963e5944c7ce3fcce3a080084d3f154c93c67b

A new release is published.
